apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: bbw-kafka-producer
spec:
  selector:
    matchLabels:
      app: bbw-kafka-producer
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: bbw-kafka-producer
    spec:
      containers:
      - env:
        - name: BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: bbw-config
              key: BOOTSTRAP_SERVERS
        - name: CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: bbw-config
              key: CLIENT_ID
        image: niharkapadia/bbw-kafka-producer:1.0
        imagePullPolicy: Always
        name: bbw-kafka-producer
        ports:
        - containerPort: 8080
# The port that the container is running on in the cluster