kind: Service
apiVersion: v1
metadata:
  name: bbw-kafka-producer-svc
spec:
  type: LoadBalancer
  selector:
    app: bbw-kafka-producer
  ports:
    - port: 8080
      targetPort: 8081
      name: app